import type { SyntheticNlpCase } from './evaluationCorpus.js';

// Additional local representative descriptions used by Stage 17. They remain
// synthetic and explicitly labeled so evaluation never treats live user data
// as ground truth.
export const REPRESENTATIVE_NLP_CASES = [
  {
    id: 'representative-linux-experience',
    kind: 'coverage',
    text: 'We require hands-on Linux administration with 3 years of experience.',
    expectedCategories: ['skill', 'experience'],
    expectedStrength: 'required',
    expectedEntities: [
      { type: 'text', value: 'linux' },
      { type: 'years', value: '3' },
    ],
    forbiddenCategories: [],
    rationale: 'Representative combined skill and experience requirement.',
  },
  {
    id: 'representative-master-preferred',
    kind: 'coverage',
    text: "A master's degree in information systems is preferred.",
    expectedCategories: ['education'],
    expectedStrength: 'preferred',
    expectedEntities: [{ type: 'degree-level', value: 'master' }],
    forbiddenCategories: [],
    rationale: 'Representative preferred education requirement.',
  },
  {
    id: 'representative-work-authorization',
    kind: 'coverage',
    text: 'Candidates must have unrestricted authorization to work in the United States.',
    expectedCategories: ['citizenship'],
    expectedStrength: 'required',
    expectedEntities: [{ type: 'text', value: 'work-authorization' }],
    forbiddenCategories: [],
    rationale: 'Representative work authorization requirement.',
  },
  {
    id: 'representative-hybrid-denver',
    kind: 'coverage',
    text: 'Hybrid schedule with three days in the office in Denver, Colorado.',
    expectedCategories: ['work-arrangement', 'schedule', 'location'],
    expectedStrength: 'informational',
    expectedEntities: [
      { type: 'city', value: 'denver' },
      { type: 'state', value: 'CO' },
    ],
    forbiddenCategories: [],
    expectedArrangement: 'hybrid',
    rationale:
      'Representative multi-label arrangement, schedule, and location.',
  },
  {
    id: 'representative-travel-percent',
    kind: 'coverage',
    text: 'Some domestic travel up to 10% may be required.',
    expectedCategories: ['travel'],
    expectedStrength: 'required',
    expectedEntities: [{ type: 'percentage', value: '10' }],
    forbiddenCategories: [],
    rationale: 'Representative bounded travel requirement.',
  },
  {
    id: 'representative-temporary-role',
    kind: 'coverage',
    text: 'The role is a six-month temporary engagement.',
    expectedCategories: ['employment-type'],
    expectedStrength: 'informational',
    expectedEntities: [],
    forbiddenCategories: [],
    rationale: 'Representative temporary employment description.',
  },
  {
    id: 'representative-firewall-duty',
    kind: 'coverage',
    text: 'Responsibilities include configuring firewalls and monitoring EDR.',
    expectedCategories: ['responsibility', 'skill'],
    expectedStrength: 'unknown',
    expectedEntities: [
      { type: 'text', value: 'firewall' },
      { type: 'text', value: 'edr' },
    ],
    forbiddenCategories: [],
    rationale: 'Representative duty with two technology mentions.',
  },
  {
    id: 'representative-hourly-compensation',
    kind: 'coverage',
    text: 'Base pay is $75 per hour plus an annual bonus.',
    expectedCategories: ['compensation'],
    expectedStrength: 'informational',
    expectedEntities: [],
    forbiddenCategories: [],
    rationale: 'Representative hourly compensation disclosure.',
  },
  {
    id: 'representative-parental-benefit',
    kind: 'coverage',
    text: 'Benefits include parental leave and a wellness program.',
    expectedCategories: ['benefit'],
    expectedStrength: 'informational',
    expectedEntities: [],
    forbiddenCategories: [],
    rationale: 'Representative benefits disclosure.',
  },
  {
    id: 'representative-global-provider',
    kind: 'coverage',
    text: 'We are a global provider of secure cloud services.',
    expectedCategories: ['company-description'],
    expectedStrength: 'informational',
    expectedEntities: [],
    forbiddenCategories: [],
    rationale: 'Representative employer description.',
  },
  {
    id: 'representative-certification-after-hire',
    kind: 'coverage',
    text: 'CySA+ must be obtained within 90 days of joining.',
    expectedCategories: ['certification'],
    expectedStrength: 'required-after-hire',
    expectedEntities: [{ type: 'certification', value: 'cysa-plus' }],
    forbiddenCategories: [],
    rationale: 'Representative post-hire certification requirement.',
  },
  {
    id: 'representative-generic-closing',
    kind: 'coverage',
    text: 'Learn more about the opportunity during the application process.',
    expectedCategories: ['unknown'],
    expectedStrength: 'informational',
    expectedEntities: [],
    forbiddenCategories: [],
    rationale: 'Representative non-requirement closing language.',
  },
] as const satisfies readonly SyntheticNlpCase[];
